# Use postgres/example user/password credentials
version: '3.1'

services:

  node-db-1:
    container_name: node-db-1
    image: postgres
    restart: "no"
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - node-network-1
    volumes:
      - ./data-node-1:/var/lib/postgresql/data

networks:
  node-network-1:
    driver: bridge