# Use postgres/example user/password credentials
version: '3.1'

services:

  node-db-1:
    container_name: node-db-1
    image: postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - node-network-1
networks:
  node-network-1:
    driver: bridge