# Use postgres/example user/password credentials
version: '3.1'

services:

  node-db-3:
    container_name: node-db-3
    image: postgres
    restart: "no"
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - node-network-3
    volumes:
      - ./data-node-3:/var/lib/postgresql/data


networks:
  node-network-3:
    driver: bridge