# Use postgres/example user/password credentials
version: '3.1'

services:

  file-storage:
    container_name: file-storage
    image: postgres
    restart: "no"
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - file-storage-network
    volumes:
      - ./data/:/var/lib/postgresql/data

networks:
  file-storage-network:
    driver: bridge